Repository studiomado/query-bundle, pull requests merged in 2018-06, with the labels that each got.

#149 improved coverage on pagerfantabuilder
  tests/Mado/QueryBundle/Objects/PagerfantaBuilderTest.php
Labels: enhancement

#152 fixed bug sorting two levels
  src/Mado/QueryBundle/Queries/QueryBuilderFactory.php
  tests/Mado/QueryBundle/Objects/QueryBuilderFactoryTest.php
Labels: hotfix

#153 accept symfony 4
  composer.json
Labels: enhancement

#154 accept other symfony4 dependencies
  composer.json
Labels: enhancement

#155 Feature/find all no paginated/2.4
  CHANGELOG-2.4.md
  README.md
  src/Mado/QueryBundle/Repositories/BaseRepository.php
Labels: feature

#156 feature/2.2/provide field usable operators
  composer.json
  composer.lock
  src/Mado/QueryBundle/Dictionary.php
  src/Mado/QueryBundle/Resources/config/services.yml
  src/Mado/QueryBundle/Services/StringParser.php
  tests/Mado/QueryBundle/Objects/QueryBuilderFactoryTest.php
Labels: feature

#157 ignore coverage because tested inside applications
  src/Mado/QueryBundle/Repositories/BaseRepository.php
Labels: coverage
