Repository studiomado/query-bundle, pull requests merged in 2018-07, with the labels that each got.

#159 explicit convert to boolean result the if statement condition
  src/Mado/QueryBundle/Component/Meta/MapBuilder.php
Labels: enhancement

#160 improved code into filter class
  src/Mado/QueryBundle/Objects/Filter.php
Labels: enhancement

#161 added miss variables into BaseRepository
  src/Mado/QueryBundle/Repositories/BaseRepository.php
Labels: enhancement

#165 fix sorting embedded two levels
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG-2.3.md
  CHANGELOG-2.4.md
  README.md
  UPGRADE-2.3.md
  UPGRADE-2.4.md
  composer.lock
  src/Mado/QueryBundle/Component/Meta/Dijkstra.php
  src/Mado/QueryBundle/Component/Meta/MapBuilder.php
  src/Mado/QueryBundle/DependencyInjection/Configuration.php
  src/Mado/QueryBundle/DependencyInjection/MadoQueryExtension.php
  src/Mado/QueryBundle/Dictionary.php
  src/Mado/QueryBundle/Dictionary/Operators.php
  src/Mado/QueryBundle/Exceptions/InvalidFiltersException.php
  src/Mado/QueryBundle/Objects/PagerfantaBuilder.php
  src/Mado/QueryBundle/Queries/AbstractQuery.php
  src/Mado/QueryBundle/Queries/AndFilter.php
  src/Mado/QueryBundle/Queries/Join.php
  src/Mado/QueryBundle/Queries/Objects/FilterObject.php
  src/Mado/QueryBundle/Queries/Objects/Operator.php
  src/Mado/QueryBundle/Queries/Objects/Value.php
  src/Mado/QueryBundle/Queries/OrFilter.php
  src/Mado/QueryBundle/Queries/QueryBuilderFactory.php
  src/Mado/QueryBundle/Queries/QueryBuilderOptions.php
  src/Mado/QueryBundle/Repositories/BaseRepository.php
  src/Mado/QueryBundle/Services/Pager.php
  src/Mado/QueryBundle/Services/Router.php
  tests/Mado/QueryBundle/Objects/PagerfantaBuilderTest.php
  tests/Mado/QueryBundle/Objects/QueryBuilderFactoryTest.php
  tests/Mado/QueryBundle/Objects/QueryBuilderOptionsTest.php
  tests/Mado/QueryBundle/Objects/ValueTest.php
  tests/Mado/QueryBundle/Queries/QueryBuilderFactoryTest.php
  tests/Mado/QueryBundle/Services/PagerTest.php
  tests/Mado/QueryBundle/Services/RouterTest.php
Labels: hotfix

#162 improve test on string parser class
  tests/Mado/QueryBundle/Services/StringParserTest.php
Labels: enhancement

#166 add the possibility to just return the count of query results
  CHANGELOG-2.2.md
  src/Mado/QueryBundle/Queries/QueryBuilderOptions.php
  src/Mado/QueryBundle/Repositories/BaseRepository.php
Labels: feature
