Repository studiomado/query-bundle, pull requests merged in 2018-05, with the labels that each got.

#118 Update documentation, some installation steps were missing
  README.md
Labels: hotfix

#126 Feature/return type and constant visibility on filter object
  src/Mado/QueryBundle/Queries/Objects/FilterObject.php
Labels: enhancement

#133 or filter generate left join instead of inner join
  CHANGELOG-2.4.md
  src/Mado/QueryBundle/Queries/QueryBuilderFactory.php
  tests/Mado/QueryBundle/Objects/QueryBuilderFactoryTest.php
Labels: hotfix

#134 Feature/operator isnull isnotnull
  CHANGELOG-2.4.md
  src/Mado/QueryBundle/Dictionary.php
  src/Mado/QueryBundle/Queries/Objects/FilterObject.php
  src/Mado/QueryBundle/Queries/QueryBuilderFactory.php
  tests/Mado/QueryBundle/Objects/QueryBuilderFactoryTest.php
Labels: feature, feature request

#135 Feature/dont add parameters in filter or if is null type
  CHANGELOG-2.4.md
  src/Mado/QueryBundle/Queries/QueryBuilderFactory.php
Labels: hotfix

#127 add Makefile to run tests and install tasks
  Makefile
Labels: enhancement

#139 removed arguments from createQueryBuilder call
  src/Mado/QueryBundle/Queries/AbstractQuery.php
  tests/Mado/QueryBundle/Objects/QueryBuilderFactoryTest.php
Labels: enhancement

#140 improve code style
  src/Mado/QueryBundle/Repositories/BaseRepository.php
Labels: enhancement

#141 move paginate function into a service
  src/Mado/QueryBundle/Objects/PagerfantaBuilder.php
  src/Mado/QueryBundle/Repositories/BaseRepository.php
  src/Mado/QueryBundle/Services/Pager.php
  tests/Mado/QueryBundle/Services/PagerTest.php
Labels: enhancement

#142 make abstract class with some abstract methods
  src/Mado/QueryBundle/Queries/AbstractQuery.php
Labels: enhancement

#143 make little improvements on unused code and style code
  src/Mado/QueryBundle/Component/Meta/Dijkstra.php
  src/Mado/QueryBundle/Component/Meta/MapBuilder.php
  src/Mado/QueryBundle/DependencyInjection/MadoQueryExtension.php
Labels: enhancement

#119 Check if filter is an array
  src/Mado/QueryBundle/Exceptions/InvalidFiltersException.php
  src/Mado/QueryBundle/Repositories/BaseRepository.php
Labels: refactoring

#144 Feature/refactor and or filter
  src/Mado/QueryBundle/Queries/AbstractQuery.php
  src/Mado/QueryBundle/Queries/AndFilter.php
  src/Mado/QueryBundle/Queries/Join.php
  src/Mado/QueryBundle/Queries/OrFilter.php
  src/Mado/QueryBundle/Queries/QueryBuilderFactory.php
  tests/Mado/QueryBundle/Objects/QueryBuilderFactoryTest.php
Labels: enhancement

#145 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: feature request

#148 add listcontains
  CHANGELOG-2.4.md
  src/Mado/QueryBundle/Dictionary.php
  src/Mado/QueryBundle/Queries/AndFilter.php
  src/Mado/QueryBundle/Queries/Objects/FilterObject.php
  tests/Mado/QueryBundle/Objects/QueryBuilderFactoryTest.php
Labels: enhancement
